config/routes.rb
Mp3Assignment::Application.routes.draw do
  resources :songs
  root :to => 'songs#index'

end

app/models/song.rb
class Song
  include Mongoid::Document
  include Mongoid::Timestamps

  #--------  Fields
  field :title
  field :artist
  field :album
  field :tracknum

  #--------- Attributes & Variables

  #--------- Relations
  mount_uploader :mp3, Mp3Uploader

  #--------- Scopes
  default_scope desc(:created_at)

  #--------- Validations
  validates_presence_of :mp3

  def self.search(query)
    if query.blank?
      scoped
    else query
    reg_term = /.*#{query}.*/i
    any_of({title: reg_term},{album: reg_term},{artist: reg_term})
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  # GET /songs
  # GET /songs.json
  before_filter :find_song ,except: [:create,:index,:new]
  before_filter :get_mp3_tag_info,only: [:create]
  def index
    @songs = Song.search(params[:query])
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @songs }
    end
  end

  # GET /songs/1
  # GET /songs/1.json
  def show


    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @song }
    end
  end

  # GET /songs/new
  # GET /songs/new.json
  def new
    @song = Song.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @song }
    end
  end

  # GET /songs/1/edit
  def edit

  end

  # POST /songs
  # POST /songs.json
  def create
    @song = Song.new(params[:song])
    respond_to do |format|
      if @song.save
        format.html { redirect_to @song, notice: 'Song was successfully created.' }
        format.json { render json: @song, status: :created, location: @song }
      else
        format.html { render action: "new" }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /songs/1
  # PUT /songs/1.json
  def update
    respond_to do |format|
      if @song.update_attributes(params[:song])
        format.html { redirect_to @song, notice: 'Song was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /songs/1
  # DELETE /songs/1.json
  def destroy
    @song.destroy
    respond_to do |format|
      format.html { redirect_to songs_url }
      format.json { head :no_content }
    end
  end

  protected
  def find_song
    @song = Song.find(params[:id])
  end

  def get_mp3_tag_info
    return unless params[:song]  and params[:song][:mp3]
    file = params[:song][:mp3]
    #ext = MIME::Types[file.content_type].first.extensions.first #better to check with myme type
    path = file.respond_to?(:path) ? file.path : file.tempfile.path
    if file.original_filename =~ /.mp3$/
      Mp3Info.open(path) do |r|
        @title = r.tag.title
        @artist = r.tag.artist
        @album = r.tag.album
        @tracknum = r.tag.tracknum
      end
    end
    params[:song].merge!(title: @title,artist: @artist,album: @album,tracknum: @tracknum)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mp3Assignment</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/songs/_form.html.haml
= form_for @song do |f|
  - if @song.errors.any?
    #error_explanation
      %h2= "#{pluralize(@song.errors.count, "error")} prohibited this song from being saved:"
      %ul
        - @song.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :upload_mp3_file
    = f.file_field :mp3
  .actions
    = f.submit 'Save'

app/views/songs/edit.html.haml
%h1 Editing song

= render 'form'

= link_to 'Show', @song
\|
= link_to 'Back', songs_path

app/views/songs/index.html.haml
%h1 Listing songs
.search_songs{style: 'padding: 10px;'}
  = form_tag songs_path,method: :get do
    = text_field_tag :query ,params[:query]
    = submit_tag 'Search' ,disable_with: 'wait ..'
    = link_to 'Refresh', songs_path


%table{border: 1}
  %tr
    %th Album
    %th Title
    %th Artist
    %th Tracknum
    %th
    %th
    %th

  - @songs.each do |song|
    %tr
      %td= song.album
      %td= song.title
      %td= song.artist
      %td= song.tracknum
      %td= link_to 'Show/Play', song
      %td= link_to 'Edit', edit_song_path(song)
      %td= link_to 'Destroy', song, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Song', new_song_path

app/views/songs/new.html.haml
%h1 New song

= render 'form'

= link_to 'Back', songs_path

app/views/songs/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @song.title
%p
  %b Album:
  = @song.album
%p
  %b Artist:
  = @song.artist

%p
  %b HTML5 Audio:
  = audio_tag(@song.mp3.url, controls: true)
= link_to 'Edit', edit_song_path(@song)
\|
= link_to 'Back', songs_path